# Generated by Django 3.2.8 on 2021-10-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('raison_sociale', models.TextField(verbose_name='raison sociale')),
                ('nombre_salaries', models.IntegerField(blank=True, null=True, verbose_name='nombre de salariés')),
                ('siren', models.CharField(max_length=9, verbose_name='siren')),
                ('region', models.CharField(blank=True, max_length=40, null=True, verbose_name='région du siège')),
                ('naf', models.CharField(blank=True, max_length=20, null=True, verbose_name="code NAF (nomenclature d'activités française)")),
                ('annee', models.IntegerField(verbose_name='année')),
                ('gestionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bilan',
                'verbose_name_plural': 'bilans',
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur')),
                ('type', models.CharField(max_length=20, verbose_name="type d'emission")),
                ('unite', models.CharField(max_length=10, verbose_name='unité')),
                ('poste', models.IntegerField(verbose_name='poste')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.report')),
            ],
            options={
                'verbose_name': 'emission',
                'verbose_name_plural': 'emissions',
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('siren', 'annee'), name='annual_report'),
        ),
    ]
