# Generated by Django 3.2.8 on 2021-12-02 15:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ademe_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='identifiant ADEME')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Draft'), ('publié', 'Published')], default='brouillon', max_length=10)),
                ('raison_sociale', models.TextField(verbose_name='raison sociale')),
                ('nombre_salaries', models.IntegerField(blank=True, null=True, verbose_name='nombre de salariés')),
                ('siren', models.CharField(max_length=9, verbose_name='siren')),
                ('region', models.CharField(blank=True, choices=[('01', '01 - Guadeloupe'), ('02', '02 - Martinique'), ('03', '03 - Guyane'), ('04', '04 - La Réunion'), ('06', '06 - Mayotte'), ('11', '11 - Île-de-France'), ('24', '24 - Centre-Val de Loire'), ('27', '27 - Bourgogne-Franche-Comté'), ('28', '28 - Normandie'), ('32', '32 - Hauts-de-France'), ('44', '44 - Grand Est'), ('52', '52 - Pays de la Loire'), ('53', '53 - Bretagne'), ('75', '75 - Nouvelle-Aquitaine'), ('76', '76 - Occitanie'), ('84', '84 - Auvergne-Rhône-Alpes'), ('93', "93 - Provence-Alpes-Côte d'Azur"), ('94', '94 - Corse')], max_length=4, null=True, verbose_name='région du siège')),
                ('naf', models.CharField(blank=True, choices=[('01', 'Culture et production animale, chasse et services annexes'), ('02', 'Sylviculture et exploitation forestière'), ('03', 'Pêche et aquaculture'), ('05', 'Extraction de houille et de lignite'), ('06', "Extraction d'hydrocarbures"), ('07', 'Extraction de minerais métalliques'), ('08', 'Autres industries extractives'), ('09', 'Services de soutien aux industries extractives'), ('10', 'Industries alimentaires'), ('11', 'Fabrication de boissons'), ('12', 'Fabrication de produits à base de tabac'), ('13', 'Fabrication de textiles'), ('14', "Industrie de l'habillement"), ('15', 'Industrie du cuir et de la chaussure'), ('16', "Travail du bois et fabrication d'articles en bois et en liège, à l'exception des meubles ; fabrication d'articles en vannerie et sparterie"), ('17', 'Industrie du papier et du carton'), ('18', "Imprimerie et reproduction d'enregistrements"), ('19', 'Cokéfaction et raffinage'), ('20', 'Industrie chimique'), ('21', 'Industrie pharmaceutique'), ('22', 'Fabrication de produits en caoutchouc et en plastique'), ('23', "Fabrication d'autres produits minéraux non métalliques"), ('24', 'Métallurgie'), ('25', "Fabrication de produits métalliques, à l'exception des machines et des équipements"), ('26', 'Fabrication de produits informatiques, électroniques et optiques'), ('27', "Fabrication d'équipements électriques"), ('28', 'Fabrication de machines et équipements n.c.a.'), ('29', 'Industrie automobile'), ('30', "Fabrication d'autres matériels de transport"), ('31', 'Fabrication de meubles'), ('32', 'Autres industries manufacturières'), ('33', "Réparation et installation de machines et d'équipements"), ('35', "Production et distribution d'électricité, de gaz, de vapeur et d'air conditionné"), ('36', "Captage, traitement et distribution d'eau"), ('37', 'Collecte et traitement des eaux usées'), ('38', 'Collecte, traitement et élimination des déchets ; récupération'), ('39', 'Dépollution et autres services de gestion des déchets'), ('41', 'Construction de bâtiments'), ('42', 'Génie civil'), ('43', 'Travaux de construction spécialisés'), ('45', "Commerce et réparation d'automobiles et de motocycles"), ('46', "Commerce de gros, à l'exception des automobiles et des motocycles"), ('47', "Commerce de détail, à l'exception des automobiles et des motocycles"), ('49', 'Transports terrestres et transport par conduites'), ('50', 'Transports par eau'), ('51', 'Transports aériens'), ('52', 'Entreposage et services auxiliaires des transports'), ('53', 'Activités de poste et de courrier'), ('55', 'Hébergement'), ('56', 'Restauration'), ('58', 'Édition'), ('59', 'Production de films cinématographiques, de vidéo et de programmes de télévision ; enregistrement sonore et édition musicale'), ('60', 'Programmation et diffusion'), ('61', 'Télécommunications'), ('62', 'Programmation, conseil et autres activités informatiques'), ('63', "Services d'information"), ('64', 'Activités des services financiers, hors assurance et caisses de retraite'), ('65', 'Assurance'), ('66', "Activités auxiliaires de services financiers et d'assurance"), ('68', 'Activités immobilières'), ('69', 'Activités juridiques et comptables'), ('70', 'Activités des sièges sociaux ; conseil de gestion'), ('71', "Activités d'architecture et d'ingénierie ; activités de contrôle et analyses techniques"), ('72', 'Recherche-développement scientifique'), ('73', 'Publicité et études de marché'), ('74', 'Autres activités spécialisées, scientifiques et techniques'), ('75', 'Activités vétérinaires'), ('77', 'Activités de location et location-bail'), ('78', "Activités liées à l'emploi"), ('79', 'Activités des agences de voyage, voyagistes, services de réservation et activités connexes'), ('80', 'Enquêtes et sécurité'), ('81', 'Services relatifs aux bâtiments et aménagement paysager'), ('82', 'Activités administratives et autres activités de soutien aux entreprises'), ('84', 'Administration publique et défense ; sécurité sociale obligatoire'), ('85', 'Enseignement'), ('86', 'Activités pour la santé humaine'), ('87', 'Hébergement médico-social et social'), ('88', 'Action sociale sans hébergement'), ('90', 'Activités créatives, artistiques et de spectacle'), ('91', 'Bibliothèques, archives, musées et autres activités culturelles'), ('92', "Organisation de jeux de hasard et d'argent"), ('93', 'Activités sportives, récréatives et de loisirs'), ('94', 'Activités des organisations associatives'), ('95', "Réparation d'ordinateurs et de biens personnels et domestiques"), ('96', 'Autres services personnels'), ('97', "Activités des ménages en tant qu'employeurs de personnel domestique"), ('98', 'Activités indifférenciées des ménages en tant que producteurs de biens et services pour usage propre'), ('99', 'Activités des organisations et organismes extraterritoriaux')], max_length=4, null=True, verbose_name="code NAF (nomenclature d'activités française)")),
                ('annee', models.IntegerField(verbose_name='année')),
                ('manuel_poste_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total poste 1 (manuel)')),
                ('manuel_poste_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total poste 2 (manuel)')),
                ('mode', models.CharField(choices=[('manuel', 'Manual'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('gestionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bilan',
                'verbose_name_plural': 'bilans',
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur')),
                ('type', models.CharField(max_length=100, verbose_name="type d'emission")),
                ('localisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='localisation')),
                ('unite', models.CharField(max_length=20, verbose_name='unité')),
                ('poste', models.IntegerField(verbose_name='poste')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.report')),
            ],
            options={
                'verbose_name': 'emission',
                'verbose_name_plural': 'emissions',
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('siren', 'annee'), name='annual_report'),
        ),
    ]
