# Generated by Django 3.2.8 on 2021-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Draft'), ('publié', 'Published')], default='brouillon', max_length=10),
        ),
    ]
