# Generated by Django 3.2.8 on 2021-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_report_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='type',
            field=models.CharField(max_length=100, verbose_name="type d'emission"),
        ),
        migrations.AlterField(
            model_name='emission',
            name='unite',
            field=models.CharField(max_length=20, verbose_name='unité'),
        ),
    ]
