# Generated by Django 3.2.8 on 2021-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_report_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='manuel_poste_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='total poste 1 (manuel)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='manuel_poste_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='total poste 2 (manuel)'),
        ),
    ]
