# Generated by Django 3.2.8 on 2021-11-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_emission_extend_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='manuel_poste_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total poste 1 (manuel)'),
        ),
        migrations.AddField(
            model_name='report',
            name='manuel_poste_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total poste 2 (manuel)'),
        ),
        migrations.AddField(
            model_name='report',
            name='mode',
            field=models.CharField(choices=[('manuel', 'Manual'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
    ]
