# Generated by Django 3.2.8 on 2021-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_add_manual_post_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='localisation'),
        ),
    ]
