# Generated by Django 3.2.10 on 2021-12-17 15:30

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_report_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='annee',
            field=models.IntegerField(validators=[data.validators.validate_report_year], verbose_name='année de reporting'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nombre_salaries',
            field=models.IntegerField(blank=True, null=True, validators=[data.validators.validate_employee_count], verbose_name='nombre de salariés'),
        ),
    ]
